// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package ticket

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Ticket                  protoreflect.MessageDescriptor
	fd_Ticket_index            protoreflect.FieldDescriptor
	fd_Ticket_eventIndex       protoreflect.FieldDescriptor
	fd_Ticket_eventDayIndex    protoreflect.FieldDescriptor
	fd_Ticket_owner            protoreflect.FieldDescriptor
	fd_Ticket_price            protoreflect.FieldDescriptor
	fd_Ticket_status           protoreflect.FieldDescriptor
	fd_Ticket_metadata         protoreflect.FieldDescriptor
	fd_Ticket_transferCount    protoreflect.FieldDescriptor
	fd_Ticket_lastTransferTime protoreflect.FieldDescriptor
	fd_Ticket_validatedAt      protoreflect.FieldDescriptor
	fd_Ticket_validatedBy      protoreflect.FieldDescriptor
)

func init() {
	file_tickfyblockchain_ticket_ticket_proto_init()
	md_Ticket = File_tickfyblockchain_ticket_ticket_proto.Messages().ByName("Ticket")
	fd_Ticket_index = md_Ticket.Fields().ByName("index")
	fd_Ticket_eventIndex = md_Ticket.Fields().ByName("eventIndex")
	fd_Ticket_eventDayIndex = md_Ticket.Fields().ByName("eventDayIndex")
	fd_Ticket_owner = md_Ticket.Fields().ByName("owner")
	fd_Ticket_price = md_Ticket.Fields().ByName("price")
	fd_Ticket_status = md_Ticket.Fields().ByName("status")
	fd_Ticket_metadata = md_Ticket.Fields().ByName("metadata")
	fd_Ticket_transferCount = md_Ticket.Fields().ByName("transferCount")
	fd_Ticket_lastTransferTime = md_Ticket.Fields().ByName("lastTransferTime")
	fd_Ticket_validatedAt = md_Ticket.Fields().ByName("validatedAt")
	fd_Ticket_validatedBy = md_Ticket.Fields().ByName("validatedBy")
}

var _ protoreflect.Message = (*fastReflection_Ticket)(nil)

type fastReflection_Ticket Ticket

func (x *Ticket) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Ticket)(x)
}

func (x *Ticket) slowProtoReflect() protoreflect.Message {
	mi := &file_tickfyblockchain_ticket_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Ticket_messageType fastReflection_Ticket_messageType
var _ protoreflect.MessageType = fastReflection_Ticket_messageType{}

type fastReflection_Ticket_messageType struct{}

func (x fastReflection_Ticket_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Ticket)(nil)
}
func (x fastReflection_Ticket_messageType) New() protoreflect.Message {
	return new(fastReflection_Ticket)
}
func (x fastReflection_Ticket_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Ticket
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Ticket) Descriptor() protoreflect.MessageDescriptor {
	return md_Ticket
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Ticket) Type() protoreflect.MessageType {
	return _fastReflection_Ticket_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Ticket) New() protoreflect.Message {
	return new(fastReflection_Ticket)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Ticket) Interface() protoreflect.ProtoMessage {
	return (*Ticket)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Ticket) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_Ticket_index, value) {
			return
		}
	}
	if x.EventIndex != "" {
		value := protoreflect.ValueOfString(x.EventIndex)
		if !f(fd_Ticket_eventIndex, value) {
			return
		}
	}
	if x.EventDayIndex != "" {
		value := protoreflect.ValueOfString(x.EventDayIndex)
		if !f(fd_Ticket_eventDayIndex, value) {
			return
		}
	}
	if x.Owner != "" {
		value := protoreflect.ValueOfString(x.Owner)
		if !f(fd_Ticket_owner, value) {
			return
		}
	}
	if x.Price != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Price)
		if !f(fd_Ticket_price, value) {
			return
		}
	}
	if x.Status != "" {
		value := protoreflect.ValueOfString(x.Status)
		if !f(fd_Ticket_status, value) {
			return
		}
	}
	if x.Metadata != "" {
		value := protoreflect.ValueOfString(x.Metadata)
		if !f(fd_Ticket_metadata, value) {
			return
		}
	}
	if x.TransferCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TransferCount)
		if !f(fd_Ticket_transferCount, value) {
			return
		}
	}
	if x.LastTransferTime != "" {
		value := protoreflect.ValueOfString(x.LastTransferTime)
		if !f(fd_Ticket_lastTransferTime, value) {
			return
		}
	}
	if x.ValidatedAt != "" {
		value := protoreflect.ValueOfString(x.ValidatedAt)
		if !f(fd_Ticket_validatedAt, value) {
			return
		}
	}
	if x.ValidatedBy != "" {
		value := protoreflect.ValueOfString(x.ValidatedBy)
		if !f(fd_Ticket_validatedBy, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Ticket) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "tickfyblockchain.ticket.Ticket.index":
		return x.Index != ""
	case "tickfyblockchain.ticket.Ticket.eventIndex":
		return x.EventIndex != ""
	case "tickfyblockchain.ticket.Ticket.eventDayIndex":
		return x.EventDayIndex != ""
	case "tickfyblockchain.ticket.Ticket.owner":
		return x.Owner != ""
	case "tickfyblockchain.ticket.Ticket.price":
		return x.Price != uint64(0)
	case "tickfyblockchain.ticket.Ticket.status":
		return x.Status != ""
	case "tickfyblockchain.ticket.Ticket.metadata":
		return x.Metadata != ""
	case "tickfyblockchain.ticket.Ticket.transferCount":
		return x.TransferCount != uint64(0)
	case "tickfyblockchain.ticket.Ticket.lastTransferTime":
		return x.LastTransferTime != ""
	case "tickfyblockchain.ticket.Ticket.validatedAt":
		return x.ValidatedAt != ""
	case "tickfyblockchain.ticket.Ticket.validatedBy":
		return x.ValidatedBy != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tickfyblockchain.ticket.Ticket"))
		}
		panic(fmt.Errorf("message tickfyblockchain.ticket.Ticket does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Ticket) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "tickfyblockchain.ticket.Ticket.index":
		x.Index = ""
	case "tickfyblockchain.ticket.Ticket.eventIndex":
		x.EventIndex = ""
	case "tickfyblockchain.ticket.Ticket.eventDayIndex":
		x.EventDayIndex = ""
	case "tickfyblockchain.ticket.Ticket.owner":
		x.Owner = ""
	case "tickfyblockchain.ticket.Ticket.price":
		x.Price = uint64(0)
	case "tickfyblockchain.ticket.Ticket.status":
		x.Status = ""
	case "tickfyblockchain.ticket.Ticket.metadata":
		x.Metadata = ""
	case "tickfyblockchain.ticket.Ticket.transferCount":
		x.TransferCount = uint64(0)
	case "tickfyblockchain.ticket.Ticket.lastTransferTime":
		x.LastTransferTime = ""
	case "tickfyblockchain.ticket.Ticket.validatedAt":
		x.ValidatedAt = ""
	case "tickfyblockchain.ticket.Ticket.validatedBy":
		x.ValidatedBy = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tickfyblockchain.ticket.Ticket"))
		}
		panic(fmt.Errorf("message tickfyblockchain.ticket.Ticket does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Ticket) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "tickfyblockchain.ticket.Ticket.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.eventIndex":
		value := x.EventIndex
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.eventDayIndex":
		value := x.EventDayIndex
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.owner":
		value := x.Owner
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.price":
		value := x.Price
		return protoreflect.ValueOfUint64(value)
	case "tickfyblockchain.ticket.Ticket.status":
		value := x.Status
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.metadata":
		value := x.Metadata
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.transferCount":
		value := x.TransferCount
		return protoreflect.ValueOfUint64(value)
	case "tickfyblockchain.ticket.Ticket.lastTransferTime":
		value := x.LastTransferTime
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.validatedAt":
		value := x.ValidatedAt
		return protoreflect.ValueOfString(value)
	case "tickfyblockchain.ticket.Ticket.validatedBy":
		value := x.ValidatedBy
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tickfyblockchain.ticket.Ticket"))
		}
		panic(fmt.Errorf("message tickfyblockchain.ticket.Ticket does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Ticket) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "tickfyblockchain.ticket.Ticket.index":
		x.Index = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.eventIndex":
		x.EventIndex = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.eventDayIndex":
		x.EventDayIndex = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.owner":
		x.Owner = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.price":
		x.Price = value.Uint()
	case "tickfyblockchain.ticket.Ticket.status":
		x.Status = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.metadata":
		x.Metadata = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.transferCount":
		x.TransferCount = value.Uint()
	case "tickfyblockchain.ticket.Ticket.lastTransferTime":
		x.LastTransferTime = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.validatedAt":
		x.ValidatedAt = value.Interface().(string)
	case "tickfyblockchain.ticket.Ticket.validatedBy":
		x.ValidatedBy = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tickfyblockchain.ticket.Ticket"))
		}
		panic(fmt.Errorf("message tickfyblockchain.ticket.Ticket does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Ticket) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "tickfyblockchain.ticket.Ticket.index":
		panic(fmt.Errorf("field index of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.eventIndex":
		panic(fmt.Errorf("field eventIndex of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.eventDayIndex":
		panic(fmt.Errorf("field eventDayIndex of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.owner":
		panic(fmt.Errorf("field owner of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.price":
		panic(fmt.Errorf("field price of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.status":
		panic(fmt.Errorf("field status of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.metadata":
		panic(fmt.Errorf("field metadata of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.transferCount":
		panic(fmt.Errorf("field transferCount of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.lastTransferTime":
		panic(fmt.Errorf("field lastTransferTime of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.validatedAt":
		panic(fmt.Errorf("field validatedAt of message tickfyblockchain.ticket.Ticket is not mutable"))
	case "tickfyblockchain.ticket.Ticket.validatedBy":
		panic(fmt.Errorf("field validatedBy of message tickfyblockchain.ticket.Ticket is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tickfyblockchain.ticket.Ticket"))
		}
		panic(fmt.Errorf("message tickfyblockchain.ticket.Ticket does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Ticket) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "tickfyblockchain.ticket.Ticket.index":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.eventIndex":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.eventDayIndex":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.owner":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.price":
		return protoreflect.ValueOfUint64(uint64(0))
	case "tickfyblockchain.ticket.Ticket.status":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.metadata":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.transferCount":
		return protoreflect.ValueOfUint64(uint64(0))
	case "tickfyblockchain.ticket.Ticket.lastTransferTime":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.validatedAt":
		return protoreflect.ValueOfString("")
	case "tickfyblockchain.ticket.Ticket.validatedBy":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: tickfyblockchain.ticket.Ticket"))
		}
		panic(fmt.Errorf("message tickfyblockchain.ticket.Ticket does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Ticket) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in tickfyblockchain.ticket.Ticket", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Ticket) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Ticket) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Ticket) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Ticket) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Ticket)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EventIndex)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EventDayIndex)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Owner)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Price != 0 {
			n += 1 + runtime.Sov(uint64(x.Price))
		}
		l = len(x.Status)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Metadata)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.TransferCount != 0 {
			n += 1 + runtime.Sov(uint64(x.TransferCount))
		}
		l = len(x.LastTransferTime)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ValidatedAt)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ValidatedBy)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Ticket)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ValidatedBy) > 0 {
			i -= len(x.ValidatedBy)
			copy(dAtA[i:], x.ValidatedBy)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ValidatedBy)))
			i--
			dAtA[i] = 0x5a
		}
		if len(x.ValidatedAt) > 0 {
			i -= len(x.ValidatedAt)
			copy(dAtA[i:], x.ValidatedAt)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ValidatedAt)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.LastTransferTime) > 0 {
			i -= len(x.LastTransferTime)
			copy(dAtA[i:], x.LastTransferTime)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LastTransferTime)))
			i--
			dAtA[i] = 0x4a
		}
		if x.TransferCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TransferCount))
			i--
			dAtA[i] = 0x40
		}
		if len(x.Metadata) > 0 {
			i -= len(x.Metadata)
			copy(dAtA[i:], x.Metadata)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Metadata)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.Status) > 0 {
			i -= len(x.Status)
			copy(dAtA[i:], x.Status)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Status)))
			i--
			dAtA[i] = 0x32
		}
		if x.Price != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Price))
			i--
			dAtA[i] = 0x28
		}
		if len(x.Owner) > 0 {
			i -= len(x.Owner)
			copy(dAtA[i:], x.Owner)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Owner)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.EventDayIndex) > 0 {
			i -= len(x.EventDayIndex)
			copy(dAtA[i:], x.EventDayIndex)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EventDayIndex)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.EventIndex) > 0 {
			i -= len(x.EventIndex)
			copy(dAtA[i:], x.EventIndex)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EventIndex)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Ticket)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Ticket: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Ticket: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EventIndex", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EventIndex = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EventDayIndex", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EventDayIndex = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Owner = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
				}
				x.Price = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Price |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Status = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Metadata = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TransferCount", wireType)
				}
				x.TransferCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TransferCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LastTransferTime", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LastTransferTime = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ValidatedAt", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ValidatedAt = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ValidatedBy", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ValidatedBy = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: tickfyblockchain/ticket/ticket.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index            string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	EventIndex       string `protobuf:"bytes,2,opt,name=eventIndex,proto3" json:"eventIndex,omitempty"`
	EventDayIndex    string `protobuf:"bytes,3,opt,name=eventDayIndex,proto3" json:"eventDayIndex,omitempty"`
	Owner            string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Price            uint64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Status           string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Metadata         string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransferCount    uint64 `protobuf:"varint,8,opt,name=transferCount,proto3" json:"transferCount,omitempty"`
	LastTransferTime string `protobuf:"bytes,9,opt,name=lastTransferTime,proto3" json:"lastTransferTime,omitempty"`
	ValidatedAt      string `protobuf:"bytes,10,opt,name=validatedAt,proto3" json:"validatedAt,omitempty"`
	ValidatedBy      string `protobuf:"bytes,11,opt,name=validatedBy,proto3" json:"validatedBy,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tickfyblockchain_ticket_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_tickfyblockchain_ticket_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Ticket) GetEventIndex() string {
	if x != nil {
		return x.EventIndex
	}
	return ""
}

func (x *Ticket) GetEventDayIndex() string {
	if x != nil {
		return x.EventDayIndex
	}
	return ""
}

func (x *Ticket) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Ticket) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ticket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ticket) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Ticket) GetTransferCount() uint64 {
	if x != nil {
		return x.TransferCount
	}
	return 0
}

func (x *Ticket) GetLastTransferTime() string {
	if x != nil {
		return x.LastTransferTime
	}
	return ""
}

func (x *Ticket) GetValidatedAt() string {
	if x != nil {
		return x.ValidatedAt
	}
	return ""
}

func (x *Ticket) GetValidatedBy() string {
	if x != nil {
		return x.ValidatedBy
	}
	return ""
}

var File_tickfyblockchain_ticket_ticket_proto protoreflect.FileDescriptor

var file_tickfyblockchain_ticket_ticket_proto_rawDesc = []byte{
	0x0a, 0x24, 0x74, 0x69, 0x63, 0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x74, 0x69, 0x63, 0x6b, 0x66, 0x79, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22,
	0xda, 0x02, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x24, 0x0a, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x79, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61,
	0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x10,
	0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x42, 0xd6, 0x01, 0x0a,
	0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x0b, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2d, 0x74, 0x69, 0x63,
	0x6b, 0x66, 0x79, 0x2d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0xa2, 0x02, 0x03, 0x54, 0x54, 0x58,
	0xaa, 0x02, 0x17, 0x54, 0x69, 0x63, 0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0xca, 0x02, 0x17, 0x54, 0x69, 0x63,
	0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0xe2, 0x02, 0x23, 0x54, 0x69, 0x63, 0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x18, 0x54, 0x69, 0x63,
	0x6b, 0x66, 0x79, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tickfyblockchain_ticket_ticket_proto_rawDescOnce sync.Once
	file_tickfyblockchain_ticket_ticket_proto_rawDescData = file_tickfyblockchain_ticket_ticket_proto_rawDesc
)

func file_tickfyblockchain_ticket_ticket_proto_rawDescGZIP() []byte {
	file_tickfyblockchain_ticket_ticket_proto_rawDescOnce.Do(func() {
		file_tickfyblockchain_ticket_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_tickfyblockchain_ticket_ticket_proto_rawDescData)
	})
	return file_tickfyblockchain_ticket_ticket_proto_rawDescData
}

var file_tickfyblockchain_ticket_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tickfyblockchain_ticket_ticket_proto_goTypes = []interface{}{
	(*Ticket)(nil), // 0: tickfyblockchain.ticket.Ticket
}
var file_tickfyblockchain_ticket_ticket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tickfyblockchain_ticket_ticket_proto_init() }
func file_tickfyblockchain_ticket_ticket_proto_init() {
	if File_tickfyblockchain_ticket_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tickfyblockchain_ticket_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tickfyblockchain_ticket_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tickfyblockchain_ticket_ticket_proto_goTypes,
		DependencyIndexes: file_tickfyblockchain_ticket_ticket_proto_depIdxs,
		MessageInfos:      file_tickfyblockchain_ticket_ticket_proto_msgTypes,
	}.Build()
	File_tickfyblockchain_ticket_ticket_proto = out.File
	file_tickfyblockchain_ticket_ticket_proto_rawDesc = nil
	file_tickfyblockchain_ticket_ticket_proto_goTypes = nil
	file_tickfyblockchain_ticket_ticket_proto_depIdxs = nil
}
