// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: tickfyblockchain/event/query.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName      = "/tickfyblockchain.event.Query/Params"
	Query_Event_FullMethodName       = "/tickfyblockchain.event.Query/Event"
	Query_EventAll_FullMethodName    = "/tickfyblockchain.event.Query/EventAll"
	Query_EventDay_FullMethodName    = "/tickfyblockchain.event.Query/EventDay"
	Query_EventDayAll_FullMethodName = "/tickfyblockchain.event.Query/EventDayAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Event items.
	Event(ctx context.Context, in *QueryGetEventRequest, opts ...grpc.CallOption) (*QueryGetEventResponse, error)
	EventAll(ctx context.Context, in *QueryAllEventRequest, opts ...grpc.CallOption) (*QueryAllEventResponse, error)
	// Queries a list of EventDay items.
	EventDay(ctx context.Context, in *QueryGetEventDayRequest, opts ...grpc.CallOption) (*QueryGetEventDayResponse, error)
	EventDayAll(ctx context.Context, in *QueryAllEventDayRequest, opts ...grpc.CallOption) (*QueryAllEventDayResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Event(ctx context.Context, in *QueryGetEventRequest, opts ...grpc.CallOption) (*QueryGetEventResponse, error) {
	out := new(QueryGetEventResponse)
	err := c.cc.Invoke(ctx, Query_Event_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EventAll(ctx context.Context, in *QueryAllEventRequest, opts ...grpc.CallOption) (*QueryAllEventResponse, error) {
	out := new(QueryAllEventResponse)
	err := c.cc.Invoke(ctx, Query_EventAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EventDay(ctx context.Context, in *QueryGetEventDayRequest, opts ...grpc.CallOption) (*QueryGetEventDayResponse, error) {
	out := new(QueryGetEventDayResponse)
	err := c.cc.Invoke(ctx, Query_EventDay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EventDayAll(ctx context.Context, in *QueryAllEventDayRequest, opts ...grpc.CallOption) (*QueryAllEventDayResponse, error) {
	out := new(QueryAllEventDayResponse)
	err := c.cc.Invoke(ctx, Query_EventDayAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Event items.
	Event(context.Context, *QueryGetEventRequest) (*QueryGetEventResponse, error)
	EventAll(context.Context, *QueryAllEventRequest) (*QueryAllEventResponse, error)
	// Queries a list of EventDay items.
	EventDay(context.Context, *QueryGetEventDayRequest) (*QueryGetEventDayResponse, error)
	EventDayAll(context.Context, *QueryAllEventDayRequest) (*QueryAllEventDayResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Event(context.Context, *QueryGetEventRequest) (*QueryGetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedQueryServer) EventAll(context.Context, *QueryAllEventRequest) (*QueryAllEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventAll not implemented")
}
func (UnimplementedQueryServer) EventDay(context.Context, *QueryGetEventDayRequest) (*QueryGetEventDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventDay not implemented")
}
func (UnimplementedQueryServer) EventDayAll(context.Context, *QueryAllEventDayRequest) (*QueryAllEventDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventDayAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Event_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Event(ctx, req.(*QueryGetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EventAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EventAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EventAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EventAll(ctx, req.(*QueryAllEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EventDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEventDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EventDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EventDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EventDay(ctx, req.(*QueryGetEventDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EventDayAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEventDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EventDayAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EventDayAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EventDayAll(ctx, req.(*QueryAllEventDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tickfyblockchain.event.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Event",
			Handler:    _Query_Event_Handler,
		},
		{
			MethodName: "EventAll",
			Handler:    _Query_EventAll_Handler,
		},
		{
			MethodName: "EventDay",
			Handler:    _Query_EventDay_Handler,
		},
		{
			MethodName: "EventDayAll",
			Handler:    _Query_EventDayAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tickfyblockchain/event/query.proto",
}
