// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tickfyblockchain/ticket/ticket.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Ticket struct {
	Index            string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	EventIndex       string `protobuf:"bytes,2,opt,name=eventIndex,proto3" json:"eventIndex,omitempty"`
	EventDayIndex    string `protobuf:"bytes,3,opt,name=eventDayIndex,proto3" json:"eventDayIndex,omitempty"`
	Owner            string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Price            uint64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Status           string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Metadata         string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransferCount    uint64 `protobuf:"varint,8,opt,name=transferCount,proto3" json:"transferCount,omitempty"`
	LastTransferTime string `protobuf:"bytes,9,opt,name=lastTransferTime,proto3" json:"lastTransferTime,omitempty"`
	ValidatedAt      string `protobuf:"bytes,10,opt,name=validatedAt,proto3" json:"validatedAt,omitempty"`
	ValidatedBy      string `protobuf:"bytes,11,opt,name=validatedBy,proto3" json:"validatedBy,omitempty"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c8cb5ac44d354a5, []int{0}
}
func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return m.Size()
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Ticket) GetEventIndex() string {
	if m != nil {
		return m.EventIndex
	}
	return ""
}

func (m *Ticket) GetEventDayIndex() string {
	if m != nil {
		return m.EventDayIndex
	}
	return ""
}

func (m *Ticket) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Ticket) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Ticket) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Ticket) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *Ticket) GetTransferCount() uint64 {
	if m != nil {
		return m.TransferCount
	}
	return 0
}

func (m *Ticket) GetLastTransferTime() string {
	if m != nil {
		return m.LastTransferTime
	}
	return ""
}

func (m *Ticket) GetValidatedAt() string {
	if m != nil {
		return m.ValidatedAt
	}
	return ""
}

func (m *Ticket) GetValidatedBy() string {
	if m != nil {
		return m.ValidatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*Ticket)(nil), "tickfyblockchain.ticket.Ticket")
}

func init() {
	proto.RegisterFile("tickfyblockchain/ticket/ticket.proto", fileDescriptor_1c8cb5ac44d354a5)
}

var fileDescriptor_1c8cb5ac44d354a5 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x18, 0x86, 0x73, 0xb5, 0x8d, 0xed, 0x15, 0x41, 0x0e, 0xd1, 0xc3, 0xe1, 0x08, 0xd2, 0xa1, 0x08,
	0xd6, 0xc1, 0xcd, 0xcd, 0xe8, 0xe2, 0x5a, 0x32, 0xb9, 0x5d, 0x93, 0x2b, 0x1e, 0x4d, 0x2f, 0x21,
	0xf9, 0x5a, 0x9b, 0x7f, 0xe1, 0xcf, 0x72, 0xec, 0x28, 0x4e, 0x92, 0xfc, 0x11, 0xc9, 0x77, 0xa1,
	0x24, 0x75, 0x4a, 0xde, 0xe7, 0x7b, 0x78, 0x39, 0x78, 0xe9, 0x04, 0x74, 0xb8, 0x5a, 0x16, 0x8b,
	0x38, 0x09, 0x57, 0xe1, 0xbb, 0xd4, 0xe6, 0xbe, 0x06, 0x0a, 0x9a, 0xcf, 0x2c, 0xcd, 0x12, 0x48,
	0xd8, 0xd5, 0xb1, 0x35, 0xb3, 0xe7, 0x9b, 0x9f, 0x1e, 0x75, 0x03, 0xfc, 0x65, 0x17, 0x74, 0xa0,
	0x4d, 0xa4, 0x76, 0x9c, 0x78, 0x64, 0x3a, 0x9a, 0xdb, 0xc0, 0x04, 0xa5, 0x6a, 0xab, 0x0c, 0xbc,
	0xe2, 0xa9, 0x87, 0xa7, 0x16, 0x61, 0x13, 0x7a, 0x86, 0xe9, 0x45, 0x16, 0x56, 0x39, 0x41, 0xa5,
	0x0b, 0xeb, 0xee, 0xe4, 0xc3, 0xa8, 0x8c, 0xf7, 0x6d, 0x37, 0x86, 0x9a, 0xa6, 0x99, 0x0e, 0x15,
	0x1f, 0x78, 0x64, 0xda, 0x9f, 0xdb, 0xc0, 0x2e, 0xa9, 0x9b, 0x83, 0x84, 0x4d, 0xce, 0x5d, 0x94,
	0x9b, 0xc4, 0xae, 0xe9, 0x70, 0xad, 0x40, 0x46, 0x12, 0x24, 0x3f, 0xc5, 0xcb, 0x21, 0xd7, 0xaf,
	0x80, 0x4c, 0x9a, 0x7c, 0xa9, 0xb2, 0xe7, 0x64, 0x63, 0x80, 0x0f, 0xb1, 0xb1, 0x0b, 0xd9, 0x2d,
	0x3d, 0x8f, 0x65, 0x0e, 0x41, 0x03, 0x03, 0xbd, 0x56, 0x7c, 0x84, 0x4d, 0xff, 0x38, 0xf3, 0xe8,
	0x78, 0x2b, 0x63, 0x1d, 0x49, 0x50, 0xd1, 0x13, 0x70, 0x8a, 0x5a, 0x1b, 0x75, 0x0c, 0xbf, 0xe0,
	0xe3, 0x23, 0xc3, 0x2f, 0xfc, 0xc7, 0xaf, 0x52, 0x90, 0x7d, 0x29, 0xc8, 0x6f, 0x29, 0xc8, 0x67,
	0x25, 0x9c, 0x7d, 0x25, 0x9c, 0xef, 0x4a, 0x38, 0x6f, 0x9e, 0xdd, 0xe3, 0xae, 0x35, 0xdb, 0xee,
	0x30, 0x5c, 0x91, 0xaa, 0x7c, 0xe1, 0xe2, 0x70, 0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0xb6, 0x80, 0xbb, 0xe0, 0x01, 0x00, 0x00,
}

func (m *Ticket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ticket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ticket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatedBy) > 0 {
		i -= len(m.ValidatedBy)
		copy(dAtA[i:], m.ValidatedBy)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.ValidatedBy)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ValidatedAt) > 0 {
		i -= len(m.ValidatedAt)
		copy(dAtA[i:], m.ValidatedAt)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.ValidatedAt)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LastTransferTime) > 0 {
		i -= len(m.LastTransferTime)
		copy(dAtA[i:], m.LastTransferTime)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.LastTransferTime)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TransferCount != 0 {
		i = encodeVarintTicket(dAtA, i, uint64(m.TransferCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if m.Price != 0 {
		i = encodeVarintTicket(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.EventDayIndex) > 0 {
		i -= len(m.EventDayIndex)
		copy(dAtA[i:], m.EventDayIndex)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.EventDayIndex)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EventIndex) > 0 {
		i -= len(m.EventIndex)
		copy(dAtA[i:], m.EventIndex)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.EventIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTicket(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTicket(dAtA []byte, offset int, v uint64) int {
	offset -= sovTicket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Ticket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	l = len(m.EventIndex)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	l = len(m.EventDayIndex)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovTicket(uint64(m.Price))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	if m.TransferCount != 0 {
		n += 1 + sovTicket(uint64(m.TransferCount))
	}
	l = len(m.LastTransferTime)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	l = len(m.ValidatedAt)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	l = len(m.ValidatedBy)
	if l > 0 {
		n += 1 + l + sovTicket(uint64(l))
	}
	return n
}

func sovTicket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTicket(x uint64) (n int) {
	return sovTicket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ticket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTicket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ticket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ticket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventDayIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventDayIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferCount", wireType)
			}
			m.TransferCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransferCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastTransferTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastTransferTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTicket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTicket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTicket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTicket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTicket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTicket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTicket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTicket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTicket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTicket = fmt.Errorf("proto: unexpected end of group")
)
